/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "FeatureVector_constants.h"



const FeatureVectorConstants g_FeatureVector_constants;

FeatureVectorConstants::FeatureVectorConstants() {
}



