/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "alg_mgr_constants.h"

namespace BigRLab {

const alg_mgrConstants g_alg_mgr_constants;

alg_mgrConstants::alg_mgrConstants() {
}

} // namespace

