/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef RunCmd_TYPES_TCC
#define RunCmd_TYPES_TCC

#include "AlgCommon_types.tcc"
#include "RunCmd_types.h"

namespace RunCmd {

} // namespace

#endif
