/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "RunCmd_constants.h"

namespace RunCmd {

const RunCmdConstants g_RunCmd_constants;

RunCmdConstants::RunCmdConstants() {
}

} // namespace

