/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef TopicService_H
#define TopicService_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "topics_types.h"

namespace Topics {

#ifdef _WIN32
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class TopicServiceIf {
 public:
  virtual ~TopicServiceIf() {}
  virtual void predictTopic(std::vector<Result> & _return, const std::string& text, const int32_t topk, const int32_t nIter, const int32_t perplexity, const int32_t nSkip) = 0;
  virtual void handleRequest(std::string& _return, const std::string& request) = 0;
};

class TopicServiceIfFactory {
 public:
  typedef TopicServiceIf Handler;

  virtual ~TopicServiceIfFactory() {}

  virtual TopicServiceIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(TopicServiceIf* /* handler */) = 0;
};

class TopicServiceIfSingletonFactory : virtual public TopicServiceIfFactory {
 public:
  TopicServiceIfSingletonFactory(const boost::shared_ptr<TopicServiceIf>& iface) : iface_(iface) {}
  virtual ~TopicServiceIfSingletonFactory() {}

  virtual TopicServiceIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(TopicServiceIf* /* handler */) {}

 protected:
  boost::shared_ptr<TopicServiceIf> iface_;
};

class TopicServiceNull : virtual public TopicServiceIf {
 public:
  virtual ~TopicServiceNull() {}
  void predictTopic(std::vector<Result> & /* _return */, const std::string& /* text */, const int32_t /* topk */, const int32_t /* nIter */, const int32_t /* perplexity */, const int32_t /* nSkip */) {
    return;
  }
  void handleRequest(std::string& /* _return */, const std::string& /* request */) {
    return;
  }
};

typedef struct _TopicService_predictTopic_args__isset {
  _TopicService_predictTopic_args__isset() : text(false), topk(false), nIter(false), perplexity(false), nSkip(false) {}
  bool text :1;
  bool topk :1;
  bool nIter :1;
  bool perplexity :1;
  bool nSkip :1;
} _TopicService_predictTopic_args__isset;

class TopicService_predictTopic_args {
 public:

  TopicService_predictTopic_args(const TopicService_predictTopic_args&);
  TopicService_predictTopic_args(TopicService_predictTopic_args&&);
  TopicService_predictTopic_args& operator=(const TopicService_predictTopic_args&);
  TopicService_predictTopic_args& operator=(TopicService_predictTopic_args&&);
  TopicService_predictTopic_args() : text(), topk(0), nIter(0), perplexity(0), nSkip(0) {
  }

  virtual ~TopicService_predictTopic_args() throw();
  std::string text;
  int32_t topk;
  int32_t nIter;
  int32_t perplexity;
  int32_t nSkip;

  _TopicService_predictTopic_args__isset __isset;

  void __set_text(const std::string& val);

  void __set_topk(const int32_t val);

  void __set_nIter(const int32_t val);

  void __set_perplexity(const int32_t val);

  void __set_nSkip(const int32_t val);

  template <class Protocol_>
  uint32_t read(Protocol_* iprot);
  template <class Protocol_>
  uint32_t write(Protocol_* oprot) const;

};


class TopicService_predictTopic_pargs {
 public:


  virtual ~TopicService_predictTopic_pargs() throw();
  const std::string* text;
  const int32_t* topk;
  const int32_t* nIter;
  const int32_t* perplexity;
  const int32_t* nSkip;

  template <class Protocol_>
  uint32_t write(Protocol_* oprot) const;

};

typedef struct _TopicService_predictTopic_result__isset {
  _TopicService_predictTopic_result__isset() : success(false), err(false) {}
  bool success :1;
  bool err :1;
} _TopicService_predictTopic_result__isset;

class TopicService_predictTopic_result {
 public:

  TopicService_predictTopic_result(const TopicService_predictTopic_result&);
  TopicService_predictTopic_result(TopicService_predictTopic_result&&);
  TopicService_predictTopic_result& operator=(const TopicService_predictTopic_result&);
  TopicService_predictTopic_result& operator=(TopicService_predictTopic_result&&);
  TopicService_predictTopic_result() {
  }

  virtual ~TopicService_predictTopic_result() throw();
  std::vector<Result>  success;
  InvalidRequest err;

  _TopicService_predictTopic_result__isset __isset;

  void __set_success(const std::vector<Result> & val);

  void __set_err(const InvalidRequest& val);

  template <class Protocol_>
  uint32_t read(Protocol_* iprot);
  template <class Protocol_>
  uint32_t write(Protocol_* oprot) const;

};

typedef struct _TopicService_predictTopic_presult__isset {
  _TopicService_predictTopic_presult__isset() : success(false), err(false) {}
  bool success :1;
  bool err :1;
} _TopicService_predictTopic_presult__isset;

class TopicService_predictTopic_presult {
 public:


  virtual ~TopicService_predictTopic_presult() throw();
  std::vector<Result> * success;
  InvalidRequest err;

  _TopicService_predictTopic_presult__isset __isset;

  template <class Protocol_>
  uint32_t read(Protocol_* iprot);

};

typedef struct _TopicService_handleRequest_args__isset {
  _TopicService_handleRequest_args__isset() : request(false) {}
  bool request :1;
} _TopicService_handleRequest_args__isset;

class TopicService_handleRequest_args {
 public:

  TopicService_handleRequest_args(const TopicService_handleRequest_args&);
  TopicService_handleRequest_args(TopicService_handleRequest_args&&);
  TopicService_handleRequest_args& operator=(const TopicService_handleRequest_args&);
  TopicService_handleRequest_args& operator=(TopicService_handleRequest_args&&);
  TopicService_handleRequest_args() : request() {
  }

  virtual ~TopicService_handleRequest_args() throw();
  std::string request;

  _TopicService_handleRequest_args__isset __isset;

  void __set_request(const std::string& val);

  template <class Protocol_>
  uint32_t read(Protocol_* iprot);
  template <class Protocol_>
  uint32_t write(Protocol_* oprot) const;

};


class TopicService_handleRequest_pargs {
 public:


  virtual ~TopicService_handleRequest_pargs() throw();
  const std::string* request;

  template <class Protocol_>
  uint32_t write(Protocol_* oprot) const;

};

typedef struct _TopicService_handleRequest_result__isset {
  _TopicService_handleRequest_result__isset() : success(false), err(false) {}
  bool success :1;
  bool err :1;
} _TopicService_handleRequest_result__isset;

class TopicService_handleRequest_result {
 public:

  TopicService_handleRequest_result(const TopicService_handleRequest_result&);
  TopicService_handleRequest_result(TopicService_handleRequest_result&&);
  TopicService_handleRequest_result& operator=(const TopicService_handleRequest_result&);
  TopicService_handleRequest_result& operator=(TopicService_handleRequest_result&&);
  TopicService_handleRequest_result() : success() {
  }

  virtual ~TopicService_handleRequest_result() throw();
  std::string success;
  InvalidRequest err;

  _TopicService_handleRequest_result__isset __isset;

  void __set_success(const std::string& val);

  void __set_err(const InvalidRequest& val);

  template <class Protocol_>
  uint32_t read(Protocol_* iprot);
  template <class Protocol_>
  uint32_t write(Protocol_* oprot) const;

};

typedef struct _TopicService_handleRequest_presult__isset {
  _TopicService_handleRequest_presult__isset() : success(false), err(false) {}
  bool success :1;
  bool err :1;
} _TopicService_handleRequest_presult__isset;

class TopicService_handleRequest_presult {
 public:


  virtual ~TopicService_handleRequest_presult() throw();
  std::string* success;
  InvalidRequest err;

  _TopicService_handleRequest_presult__isset __isset;

  template <class Protocol_>
  uint32_t read(Protocol_* iprot);

};

template <class Protocol_>
class TopicServiceClientT : virtual public TopicServiceIf {
 public:
  TopicServiceClientT(boost::shared_ptr< Protocol_> prot) {
    setProtocolT(prot);
  }
  TopicServiceClientT(boost::shared_ptr< Protocol_> iprot, boost::shared_ptr< Protocol_> oprot) {
    setProtocolT(iprot,oprot);
  }
 private:
  void setProtocolT(boost::shared_ptr< Protocol_> prot) {
  setProtocolT(prot,prot);
  }
  void setProtocolT(boost::shared_ptr< Protocol_> iprot, boost::shared_ptr< Protocol_> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return this->piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return this->poprot_;
  }
  void predictTopic(std::vector<Result> & _return, const std::string& text, const int32_t topk, const int32_t nIter, const int32_t perplexity, const int32_t nSkip);
  void send_predictTopic(const std::string& text, const int32_t topk, const int32_t nIter, const int32_t perplexity, const int32_t nSkip);
  void recv_predictTopic(std::vector<Result> & _return);
  void handleRequest(std::string& _return, const std::string& request);
  void send_handleRequest(const std::string& request);
  void recv_handleRequest(std::string& _return);
 protected:
  boost::shared_ptr< Protocol_> piprot_;
  boost::shared_ptr< Protocol_> poprot_;
  Protocol_* iprot_;
  Protocol_* oprot_;
};

typedef TopicServiceClientT< ::apache::thrift::protocol::TProtocol> TopicServiceClient;

template <class Protocol_>
class TopicServiceProcessorT : public ::apache::thrift::TDispatchProcessorT<Protocol_> {
 protected:
  boost::shared_ptr<TopicServiceIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
  virtual bool dispatchCallTemplated(Protocol_* iprot, Protocol_* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (TopicServiceProcessorT::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef void (TopicServiceProcessorT::*SpecializedProcessFunction)(int32_t, Protocol_*, Protocol_*, void*);
  struct ProcessFunctions {
    ProcessFunction generic;
    SpecializedProcessFunction specialized;
    ProcessFunctions(ProcessFunction g, SpecializedProcessFunction s) :
      generic(g),
      specialized(s) {}
    ProcessFunctions() : generic(NULL), specialized(NULL) {}
  };
  typedef std::map<std::string, ProcessFunctions> ProcessMap;
  ProcessMap processMap_;
  void process_predictTopic(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_predictTopic(int32_t seqid, Protocol_* iprot, Protocol_* oprot, void* callContext);
  void process_handleRequest(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_handleRequest(int32_t seqid, Protocol_* iprot, Protocol_* oprot, void* callContext);
 public:
  TopicServiceProcessorT(boost::shared_ptr<TopicServiceIf> iface) :
    iface_(iface) {
    processMap_["predictTopic"] = ProcessFunctions(
      &TopicServiceProcessorT::process_predictTopic,
      &TopicServiceProcessorT::process_predictTopic);
    processMap_["handleRequest"] = ProcessFunctions(
      &TopicServiceProcessorT::process_handleRequest,
      &TopicServiceProcessorT::process_handleRequest);
  }

  virtual ~TopicServiceProcessorT() {}
};

typedef TopicServiceProcessorT< ::apache::thrift::protocol::TDummyProtocol > TopicServiceProcessor;

template <class Protocol_>
class TopicServiceProcessorFactoryT : public ::apache::thrift::TProcessorFactory {
 public:
  TopicServiceProcessorFactoryT(const ::boost::shared_ptr< TopicServiceIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< TopicServiceIfFactory > handlerFactory_;
};

typedef TopicServiceProcessorFactoryT< ::apache::thrift::protocol::TDummyProtocol > TopicServiceProcessorFactory;

class TopicServiceMultiface : virtual public TopicServiceIf {
 public:
  TopicServiceMultiface(std::vector<boost::shared_ptr<TopicServiceIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~TopicServiceMultiface() {}
 protected:
  std::vector<boost::shared_ptr<TopicServiceIf> > ifaces_;
  TopicServiceMultiface() {}
  void add(boost::shared_ptr<TopicServiceIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void predictTopic(std::vector<Result> & _return, const std::string& text, const int32_t topk, const int32_t nIter, const int32_t perplexity, const int32_t nSkip) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->predictTopic(_return, text, topk, nIter, perplexity, nSkip);
    }
    ifaces_[i]->predictTopic(_return, text, topk, nIter, perplexity, nSkip);
    return;
  }

  void handleRequest(std::string& _return, const std::string& request) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->handleRequest(_return, request);
    }
    ifaces_[i]->handleRequest(_return, request);
    return;
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
template <class Protocol_>
class TopicServiceConcurrentClientT : virtual public TopicServiceIf {
 public:
  TopicServiceConcurrentClientT(boost::shared_ptr< Protocol_> prot) {
    setProtocolT(prot);
  }
  TopicServiceConcurrentClientT(boost::shared_ptr< Protocol_> iprot, boost::shared_ptr< Protocol_> oprot) {
    setProtocolT(iprot,oprot);
  }
 private:
  void setProtocolT(boost::shared_ptr< Protocol_> prot) {
  setProtocolT(prot,prot);
  }
  void setProtocolT(boost::shared_ptr< Protocol_> iprot, boost::shared_ptr< Protocol_> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return this->piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return this->poprot_;
  }
  void predictTopic(std::vector<Result> & _return, const std::string& text, const int32_t topk, const int32_t nIter, const int32_t perplexity, const int32_t nSkip);
  int32_t send_predictTopic(const std::string& text, const int32_t topk, const int32_t nIter, const int32_t perplexity, const int32_t nSkip);
  void recv_predictTopic(std::vector<Result> & _return, const int32_t seqid);
  void handleRequest(std::string& _return, const std::string& request);
  int32_t send_handleRequest(const std::string& request);
  void recv_handleRequest(std::string& _return, const int32_t seqid);
 protected:
  boost::shared_ptr< Protocol_> piprot_;
  boost::shared_ptr< Protocol_> poprot_;
  Protocol_* iprot_;
  Protocol_* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

typedef TopicServiceConcurrentClientT< ::apache::thrift::protocol::TProtocol> TopicServiceConcurrentClient;

#ifdef _WIN32
  #pragma warning( pop )
#endif

} // namespace

#include "TopicService.tcc"
#include "topics_types.tcc"

#endif
