/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "AlgExcept_constants.h"

namespace AlgExcept {

const AlgExceptConstants g_AlgExcept_constants;

AlgExceptConstants::AlgExceptConstants() {
}

} // namespace

