/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "PyService.h"
#include "PyService.tcc"

namespace PyTest {


PyService_segment_args::~PyService_segment_args() throw() {
}


PyService_segment_pargs::~PyService_segment_pargs() throw() {
}


PyService_segment_result::~PyService_segment_result() throw() {
}


PyService_segment_presult::~PyService_segment_presult() throw() {
}


PyService_handleRequest_args::~PyService_handleRequest_args() throw() {
}


PyService_handleRequest_pargs::~PyService_handleRequest_pargs() throw() {
}


PyService_handleRequest_result::~PyService_handleRequest_result() throw() {
}


PyService_handleRequest_presult::~PyService_handleRequest_presult() throw() {
}

} // namespace

