/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ArticleService.h"
#include "ArticleService.tcc"

namespace Article {


ArticleService_setFilter_args::~ArticleService_setFilter_args() throw() {
}


ArticleService_setFilter_pargs::~ArticleService_setFilter_pargs() throw() {
}


ArticleService_setFilter_result::~ArticleService_setFilter_result() throw() {
}


ArticleService_setFilter_presult::~ArticleService_setFilter_presult() throw() {
}


ArticleService_wordSegment_args::~ArticleService_wordSegment_args() throw() {
}


ArticleService_wordSegment_pargs::~ArticleService_wordSegment_pargs() throw() {
}


ArticleService_wordSegment_result::~ArticleService_wordSegment_result() throw() {
}


ArticleService_wordSegment_presult::~ArticleService_wordSegment_presult() throw() {
}


ArticleService_keyword_args::~ArticleService_keyword_args() throw() {
}


ArticleService_keyword_pargs::~ArticleService_keyword_pargs() throw() {
}


ArticleService_keyword_result::~ArticleService_keyword_result() throw() {
}


ArticleService_keyword_presult::~ArticleService_keyword_presult() throw() {
}


ArticleService_tagging_args::~ArticleService_tagging_args() throw() {
}


ArticleService_tagging_pargs::~ArticleService_tagging_pargs() throw() {
}


ArticleService_tagging_result::~ArticleService_tagging_result() throw() {
}


ArticleService_tagging_presult::~ArticleService_tagging_presult() throw() {
}


ArticleService_handleRequest_args::~ArticleService_handleRequest_args() throw() {
}


ArticleService_handleRequest_pargs::~ArticleService_handleRequest_pargs() throw() {
}


ArticleService_handleRequest_result::~ArticleService_handleRequest_result() throw() {
}


ArticleService_handleRequest_presult::~ArticleService_handleRequest_presult() throw() {
}

} // namespace

