/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef article_TYPES_H
#define article_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <thrift/cxxfunctional.h>


namespace Article {

class InvalidRequest;

class Result;

typedef struct _InvalidRequest__isset {
  _InvalidRequest__isset() : reason(false) {}
  bool reason :1;
} _InvalidRequest__isset;

class InvalidRequest : public ::apache::thrift::TException {
 public:

  InvalidRequest(const InvalidRequest&);
  InvalidRequest(InvalidRequest&&);
  InvalidRequest& operator=(const InvalidRequest&);
  InvalidRequest& operator=(InvalidRequest&&);
  InvalidRequest() : reason() {
  }

  virtual ~InvalidRequest() throw();
  std::string reason;

  _InvalidRequest__isset __isset;

  void __set_reason(const std::string& val);

  template <class Protocol_>
  uint32_t read(Protocol_* iprot);
  template <class Protocol_>
  uint32_t write(Protocol_* oprot) const;

  virtual void printTo(std::ostream& out) const;
  mutable std::string thriftTExceptionMessageHolder_;
  const char* what() const throw();
};

void swap(InvalidRequest &a, InvalidRequest &b);

inline std::ostream& operator<<(std::ostream& out, const InvalidRequest& obj)
{
  obj.printTo(out);
  return out;
}

typedef struct _Result__isset {
  _Result__isset() : text(false), score(false) {}
  bool text :1;
  bool score :1;
} _Result__isset;

class Result {
 public:

  Result(const Result&);
  Result(Result&&);
  Result& operator=(const Result&);
  Result& operator=(Result&&);
  Result() : text(), score(0) {
  }

  virtual ~Result() throw();
  std::string text;
  double score;

  _Result__isset __isset;

  void __set_text(const std::string& val);

  void __set_score(const double val);

  template <class Protocol_>
  uint32_t read(Protocol_* iprot);
  template <class Protocol_>
  uint32_t write(Protocol_* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(Result &a, Result &b);

inline std::ostream& operator<<(std::ostream& out, const Result& obj)
{
  obj.printTo(out);
  return out;
}

} // namespace

#include "article_types.tcc"

#endif
