/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ftrl_CONSTANTS_H
#define ftrl_CONSTANTS_H

#include "ftrl_types.h"

namespace FTRL {

class ftrlConstants {
 public:
  ftrlConstants();

};

extern const ftrlConstants g_ftrl_constants;

} // namespace

#endif
