/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef alg_mgr_CONSTANTS_H
#define alg_mgr_CONSTANTS_H

#include "alg_mgr_types.h"

namespace BigRLab {

class alg_mgrConstants {
 public:
  alg_mgrConstants();

};

extern const alg_mgrConstants g_alg_mgr_constants;

} // namespace

#endif
