/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "KnnService.h"
#include "KnnService.tcc"

namespace KNN {


KnnService_queryByItem_args::~KnnService_queryByItem_args() throw() {
}


KnnService_queryByItem_pargs::~KnnService_queryByItem_pargs() throw() {
}


KnnService_queryByItem_result::~KnnService_queryByItem_result() throw() {
}


KnnService_queryByItem_presult::~KnnService_queryByItem_presult() throw() {
}


KnnService_queryByVector_args::~KnnService_queryByVector_args() throw() {
}


KnnService_queryByVector_pargs::~KnnService_queryByVector_pargs() throw() {
}


KnnService_queryByVector_result::~KnnService_queryByVector_result() throw() {
}


KnnService_queryByVector_presult::~KnnService_queryByVector_presult() throw() {
}

} // namespace

